-- 코드를 입력하세요
SELECT CRCRH.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND
CRCRH.START_DATE >= '2022-10-01' and START_DATE < '2022-11-01'
GROUP BY CRCRH.CAR_ID
ORDER BY CRCRH.CAR_ID DESC