-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE LEFT(BS.SALES_DATE, 7) LIKE "%01%"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC